### ISSUE TITLE
Document Tilt setup with another Kibana version

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-server#10662]
During development, it is sometimes necessary to test with the latest (or local) version of Kibana, for example in the following cases:
- dependency on a Kibana feature that isn't released yet, but might already be included in a snapshot version
- dependency on a Kibana feature that isn't available in a Docker image (like a local copy)

It is possible to modify the Tilt configuration by adding the following to `testing/infra/k8s/overlays/local/kustomization.yaml`:

```

- patch: |-
    apiVersion: kibana.k8s.elastic.co/v1
    kind: Kibana
    metadata:
      name: kibana
    spec:
      image: docker.elastic.co/kibana/kibana:8.8.0-SNAPSHOT
```

Where `docker.elastic.co/kibana/kibana:8.8.0-SNAPSHOT` should be replaced with the docker image name and version, or could even be a local-only docker image.

I think here we should at least document this possibility, and maybe provide a commented-out version directly into `testing/infra/k8s/overlays/local/kustomization.yaml` to make contributions easier.
