### ISSUE TITLE
"There are no ingest nodes in this cluster, unable to forward request to an ingest node" errors

### ISSUE THREAD

**Issue by khteh** [elastic/apm-server#10755]
**APM Server version** (`apm-server version`): 8.7.1

**Description of the problem including expected versus actual behavior**:
```
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: my-apmserver
  labels:
    app: apmserver
    component: eck
spec:
  version: 8.7.1
  count: 3
  secureSettings:
    - secretName: ny-es-elastic-user
  config:
    output:
      elasticsearch:
        hosts: ["my-es-internal-http.default:9200"]
        username: elastic
        password: "${elastic}"
        protocol: "https"
        ssl.certificate_authorities:
          ["/usr/share/apm-server/config/elasticsearch-ca/tls.crt"]
  podTemplate:
    spec:
      containers:
        - name: apm-server
          volumeMounts:
            - mountPath: /usr/share/apm-server/config/elasticsearch-ca
              name: elasticsearch-ca
              readOnly: true
      volumes:
        - name: elasticsearch-ca
          secret:
            defaultMode: 420
            optional: false
            secretName: elasticsearch-eck-ca # This is the secret that holds the Elasticsearch CA cert
```
```
[my-apm-server-985bdf477-hkpfv apm-server] {"log.level":"error","@timestamp":"2023-05-06T08:44:10.367Z","log.origin":{"file.name":"go-docappender@v0.1.0/appender.go","file.line":256},"message":"bulk indexing request failed","service.name":"apm-server","error":{"message":"flush failed: [500 Internal Server Error] {\"error\":{\"root_cause\":[{\"type\":\"illegal_state_exception\",\"reason\":\"There are no ingest nodes in this cluster, unable to forward request to an ingest node.\"}],\"type\":\"illegal_state_exception\",\"reason\":\"There are no ingest nodes in this cluster, unable to forward request to an ingest node.\"},\"status\":500}"},"ecs.version":"1.6.0"} 
```
What should I do?
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
