### ISSUE TITLE
RabbitMQ OTEL transactions not recognized as "messaging"

### ISSUE THREAD

**Issue by drewhammond** [elastic/apm-server#10780]
Starting with [OpenTelemetry java agent](https://github.com/open-telemetry/opentelemetry-java-instrumentation) 1.23.0, RabbitMQ transactions are being categorized as  "unknown" in the APM UI.

I believe it may be related to changes in the spec here: https://github.com/open-telemetry/opentelemetry-specification/pull/2957

**APM Server version** (`apm-server version`): 

8.7.1

**Description of the problem including expected versus actual behavior**:

Prior to 1.23.0, these `<queue> process` transactions were located under the "messaging" dropdown item in the APM UI.
Now they are found under "unknown".

**Steps to reproduce**:

 1. Create basic java RabbitMQ consumer process
 2. Attach otel java agent 1.23.0 (or newer) with auto-instrumentation and nothing fancy

```
otel.traces.exporter=otlp
otel.traces.sampler=parentbased_always_on
otel.exporter.otlp.protocol=http/protobuf
otel.exporter.otlp.traces.protocol=http/protobuf
```
3. Send traces to local opentelemetry collector (v0.73.0) that then sends to APM server using OTLP.
4. Consume messages
5. Verify in APM UI that `<queue> process` transactions are only found after selecting "unknown" transaction type dropdown

*OTEL collector config*

```
receivers:
  otlp:
    protocols:
      http:
exporters:
  otlp/local:
    endpoint: apm-server:8200
    tls:
      insecure: true
service:
  pipelines:
    traces/1:
      receivers: [otlp]
      exporters: [otlp/local]
```
