### ISSUE TITLE
mapping set to strict, dynamic introduction of [error] within [_doc] is not allowed

### ISSUE THREAD

**Issue by andremoah** [elastic/apm-server#11167]
**APM Server version** (`apm-server version`): 8.7.1

**Description of the problem including expected versus actual behavior**:
Thousands of errors all saying the same: "mapping set to strict, dynamic introduction of [error] within [_doc] is not allowed".

The Elastic Apm traces correctly appear in Kibana UI while the application is being used, but this error log appears all the time.

**Steps to reproduce**:

Did a fresh install of elasticapm version 8.7.1, connected to a self managed Elasticsearch + Kibana with APM integration installed. 

Using latest .Net and Nodejs Agents.

APM config file 

```
apm-server:
  # 0.0.0.0 allows the internet to send data to the apm server. 5700 is the port exposed by the apm server
  host: '0.0.0.0:8200'

  # denotes the maximum size of a single event in bytes that can be processed by the APM server.
  # if an event size is greater than the configured then that event is dropped
  max_event_size: 1457600

  # Maximum permitted size in bytes of a request's header accepted by the server to be processed.
  max_header_size: 485760

  # Maximum amount of time to wait for the next incoming request before underlying connection is closed.
  idle_timeout: 90s

  # Maximum permitted duration for reading an entire request.
  read_timeout: 300s

  # Maximum permitted duration for writing a response.
  write_timeout: 300s

  # refers to Real User Monitoring. When enabled the APM server can receive the performance data from the Frontend
  rum:
    enabled: false
  kibana:
    enabled: true
    host: "xxxx"
    username: "xxx"
    password: "xxx"

# denotes the number of events that can be stored in the APM memory queue.
# If the rate of events becomes higher than the speed with which Elasticsearch can process them then events can
# be queued. Higher values prevent events to be lost but may take a large amount of RAM during high traffic
queue.mem.events: 20000

# only errors will be logged in the log file
logging.level: error
logging.metrics.enabled: false

output.elasticsearch:
  hosts: [xxx]
  username: xxx
  password: xxx
  #Number of workers per Elasticsearch host.
  #More workers prevents APM queue from filling if ES can keep up with indexing
  worker: 5
  #The maximum number of events to bulk in a single Elasticsearch bulk API index request.
  #The default is 50.
  bulk_max_size: 10000
  #Configure http request timeout before failing an request to Elasticsearch.
  timeout: 300
  ssl.verification_mode: none
```

**Provide logs (if relevant)**:

![Screenshot 2023-07-10 at 10 35 19](https://github.com/elastic/apm-server/assets/8550246/9a50db5b-056e-411b-bc08-3b2f56ff2385)
