### ISSUE TITLE
apmpackage: support phases (warm, cold) in ILM in apm package

### ISSUE THREAD

**Issue by azhurbilo** [elastic/apm-server#11579]
right now, built-in ILM policies with APM package don't use Warm/Cold nodes type

it will be good to support them

<img width="1557" alt="image" src="https://github.com/elastic/apm-server/assets/6387460/8938f2de-916d-4712-99f1-d52a7579a1d9">

ideally APM package should support all customisation which ApmServer k8s CRD have

for example

```
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: xxxx
spec:
  ...
  elasticsearchRef:
    name: xxx
  kibanaRef:
    name: xxx
  config:
    logging.level: warning
    logging.json: true
    setup:
      dashboards.enabled: true
      ilm:
        enabled: true
        overwrite: true
        policy_file: "ilm-policy.json"
      template:
        settings:
          index:
            number_of_shards: 8
            number_of_replicas: 2
```
