### ISSUE TITLE
apm-server: not found via docker

### ISSUE THREAD

**Issue by jeffbeagley** [elastic/apm-server#1265]
I'm trying to setup a custom dockerfile that is called from compose.. however everytime I run it I'm receiving the error, 
`/usr/local/bin/docker-entrypoint: line 8: exec: apm-server: not found`

I've tried running it as per this documentation, https://www.elastic.co/guide/en/apm/server/master/running-on-docker.html and still receive the same error

My composer file is
```
    apm-server:
        container_name: apm-server
        build: ./apm
        links: 
            - "elasticsearch:elasticsearch"
        depends_on:
            - elasticsearch
        volumes:
            - ./apm/config:/usr/share/apm-server
```

and my dockerfile is
```
FROM elastic/apm-server:6.3.2
COPY config/apm-server.yml /usr/share/apm-server/apm-server.yml
USER root
RUN chown apm-server /usr/share/apm-server/apm-server.yml
USER apm-server

```

Appreciate any help!

**Comment by jeffbeagley** [comment]
my apm-server.yml is 

```
apm-server:
  # Defines the host and port the server is listening on.  use "unix:/path/to.sock" to listen on a unix domain socket.
  host: "localhost:8200"

#==================== Elasticsearch template setting ==========================

# Elasticsearch template settings
setup.template.settings:

  # A dictionary of settings to place into the settings.index dictionary
  # of the Elasticsearch template. For more details, please check
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html
  index:
    number_of_shards: 1
    codec: best_compression
    #number_of_routing_shards: 30

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  # Scheme and port can be left out and will be set to the default (http and 9200)
  # In case you specify and additional path, the scheme is required: http://localhost:9200/path
  # IPv6 addresses should always be defined as: https://[2001:db8::1]:9200
  hosts: ["elasticsearch:9200"]

  indices:
    - index: "apm-%{[beat.version]}-sourcemap"
      when.contains:
        processor.event: "sourcemap"

    - index: "apm-%{[beat.version]}-error-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "error"

    - index: "apm-%{[beat.version]}-transaction-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "transaction"

    - index: "apm-%{[beat.version]}-span-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "span"

    - index: "apm-%{[beat.version]}-metric-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "metric"

    - index: "apm-%{[beat.version]}-onboarding-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "onboarding"

logging.metrics.enabled: false
```
