### ISSUE TITLE
docs: OpenTelemetry Collector example exporter config is misleading

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#13551]
https://www.elastic.co/guide/get-started/current/open-telemetry-elastic.html#open-telemetry-collector has sample OpenTelemetry Collector exporter config, and uses the name "otlp/elastic" for the exporter:

```yaml
exporters:
  logging:
    loglevel: warn 
  otlp/elastic: 
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: "${ELASTIC_APM_SERVER_ENDPOINT}"  
    headers:
      # Elastic APM Server secret token
      Authorization: "Bearer ${ELASTIC_APM_SERVER_TOKEN}"
```

The "otlp/elastic" name is using the syntax described at https://opentelemetry.io/docs/collector/configuration/#exporters to name a specific instance of the "otlp" exporter:

> Note that receivers, processors, exporters and pipelines are defined through component identifiers following the type[/name] format, for example otlp or otlp/2. You can define components of a given type more than once as long as the identifiers are unique.

The inclusion of "/elastic" here may throw off users who are unfamiliar with this syntax, and trick them into thinking that they're dealing with some Elastic-specific variation of OTLP. We should remove the "/elastic".
