### ISSUE TITLE
docs: OpenTelemetry Collector example receiver config is invalid

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#13550]
https://www.elastic.co/guide/en/observability/current/apm-open-telemetry-direct.html has sample OpenTelemetry Collector receiver and exporter config, which includes this invalid snippet:

```yaml
receivers: 
  # ...
  otlp:
```

With recent versions of OpenTelemetry Collector it is necessary to specify protocols, and failing to do so will yield an error:

```
Error: invalid configuration: receivers::otlp: must specify at least one protocol when using the OTLP receiver
2024/07/02 09:46:37 collector server run finished with error: invalid configuration: receivers::otlp: must specify at least one protocol when using the OTLP receiver
```

So we should change it to, e.g.

```yaml
otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
```
