### ISSUE TITLE
Add indices defaults in code

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#1480]
Index default configuration is currently only existing in `apm-server.yml`. For people upgrading, this is problematic. Since we now have a way to override beats configuration from APM Server code, we should align the defaults so that even without an `apm-server.yml`, the right defaults are used for indices.

**Comment by roncohen** [comment]
marked it with v6.5 to show our hope that it will ship in 6.5, but not a blocker

**Comment by graphaelli** [comment]
moved the other defaults to code in #1494, default indices are proving much trickier.  I think there's actually bug in here, working on a minimal case.

**Comment by graphaelli** [comment]
After some discussion and go-ucfg schooling we've decided it's not a bug.  Unfortunately, there's also no current solution for providing a default list of indices that can be overridden by a config file / command line options.  In he strangest case, this is what happens right now:

code wants:

```
output.elasticsearch:
  hosts: ["localhost:9200"]
  indices:
    - index: "apm-%{[beat.version]}-sourcemap-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "sourcemap"
```

user config says:

```
output.elasticsearch:
  hosts: ["localhost:9200"]
  indices:
    - index: "apm-%{[beat.version]}-foo-%{+yyyy.MM.dd}"
```

actual config becomes:
```
output:
  elasticsearch:
    hosts:
    - localhost:9200
    indices:
    - index: apm-%{[beat.version]}-foo-%{+yyyy.MM.dd}
      when:
        contains:
          processor:
            event: sourcemap
```
