### ISSUE TITLE
OTLP ingested logs do not have `event.dataset` field

### ISSUE THREAD

**Issue by rauanmayemir** [elastic/apm-server#16397]
**APM Server version** (`apm-server version`): 8.17.3

**Description of the problem including expected versus actual behavior**:

When traces and logs are collected via opentelemetry-collector and then ingested through apm-server, ultimately log records indexed in ES have `data_stream.dataset` field, but not `event.dataset`.

This leads to failure to setup Anomaly Detection.

<img width="708" alt="Image" src="https://github.com/user-attachments/assets/49838830-225f-4035-a618-ce5d2abff31f" />

**Steps to reproduce**:

```
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm
spec:
  version: 8.17.3
  count: 3
  elasticsearchRef:
    name: elastic
  kibanaRef:
    name: kibana
  config:
    apm-server:
      data_streams:
        namespace: my_ns
    logging.level: warning
```
