### ISSUE TITLE
APM container image entry point. Executable not found

### ISSUE THREAD

**Issue by Javatar81** [elastic/apm-server#16958]
**APM Server version** (`apm-server version`): 9.0.1

**Description of the problem including expected versus actual behavior**:
Hardware: Apple M2
Kubernetes version: v1.27.3 (Kind cluster)
ECK Operator version: 2.16.1

APM CR is as follows:
```
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
spec:
  version: 9.0.1
  count: 1
  elasticsearchRef:
    name: backend
  kibanaRef:
    name: frontend
```

Image:         docker.elastic.co/apm/apm-server:9.0.1
Image ID:    docker.elastic.co/apm/apm-server@sha256:4d397d217e9d700afdf96bb0701e78442ae874c88e4fd7dd38398a68754dde0b

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

 1. Deploy CR for ApmServer as described above
 2. Wait for Pod to come up
 3. Container/Pod terminates
 4. kubectl describe pod <pod_name>
**Provide logs (if relevant)**:
failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "apm-server": executable file not found in $PATH: unknown
