### ISSUE TITLE
Kubernetes guides

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-server#2107]
It's still unclear how to best deploy apm-server and traced applications on Kubernetes.
Following up on some requests - #929, #1244 - and confusion - [apm-server as daemonset](https://discuss.elastic.co/t/apm-server-as-kubernetes-daemonset/161307), provide guidance for running:

- [ ] apm-server as a daemonet along the lines of [auditbeat](https://www.elastic.co/guide/en/beats/auditbeat/7.0/running-on-kubernetes.html), [filebeat](https://www.elastic.co/guide/en/beats/filebeat/7.0/running-on-kubernetes.html), and [metricbeat](https://www.elastic.co/guide/en/beats/metricbeat/7.0/running-on-kubernetes.html)
- [ ] apm-server as a deployment
- [ ] apm-server with helm
- [ ] application w/apm agent

**Comment by graphaelli** [comment]
First pass at #2112 covers daemonset and sidecar deployments, along with application w/apm agent instructions for each.  Deployment/service configuration can follow later.  Helm chart instructions will wait for https://github.com/elastic/helm-charts/issues/68 to be completed.

**Comment by sheeshmohsin** [comment]
Any updates on apm-server deployment for kubernetes?

**Comment by simitt** [comment]
@sheeshmohsin have you seen [APM Server on cloud-on-k8s](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-apm-server.html)? Let us know if that works for you.

**Comment by IzekChen** [comment]
@simitt seems like the  [APM Server on cloud-on-k8s](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-apm-server.html) cannot specify apm-server configuration like enable jaeger. right?

**Comment by simitt** [comment]
@IzekChen you can follow the [APM Server on ECK custom configuration guide](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-apm-server.html#k8s-apm-customize-configuration) to set any custom APM Server configuration, e.g. 
```
spec:
  ...
  config:
    apm-server.jaeger.grpc.enabled: true
```

**Comment by simitt** [comment]
You would also need to specify the port, so you would end up with a configuration similar to:
```
...
spec:
  ...
  config:
    apm-server.jaeger.grpc.enabled: true
    apm-server.jaeger.grpc.host: "0.0.0.0:14250"
  http:
    service:
      spec:
        ports:
          - name: http
            port: 8200
            targetPort: 8200
          - name: grpc
            port: 14250
            targetPort: 14250
```

Thanks to @charith-elastic for pointing this out.
