### ISSUE TITLE
apm-server failed connect to ElasticSearch with Xpack enabled (401 Unauthorized ) 

### ISSUE THREAD

**Issue by blump** [elastic/apm-server#2344]
Hello,

ELK_VERSION = 7.2.0

On my docker environment, I can not connect apm-server with elastic Search when xpack (basic mode) is enabled. When Xpack is disabled, it's work

> 	ERROR	pipeline/output.go:100	Failed to connect to backoff(elasticsearch(http://elasticsearch:9200)): 401 Unauthorized: {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}

While Kibana connects well with Elastic Search with Xpack (basic mode) enabled.

_config/elasticsearch.yml_
```yml
...
xpack.license.self_generated.type: basic
xpack.security.enabled: true
```
_config/kibana.yml_
```yml
...
xpack.security.enabled: true
elasticsearch.username: elastic
elasticsearch.password: changeme
```

_config/apm-server.yml_
```yml
apm-server:
  host: localhost:8200

output.elasticsearch:
    enabled: true
    protocol: "http"
    hosts: [ "elasticsearch:9200" ]
    ssl.enabled: false
    username: elastic
    password: changeme
```
How can I connect apm-server to elastic Search with Basic Authentication?

Thx !
