### ISSUE TITLE
Allow setting default ilm policy in yaml config file

### ISSUE THREAD

**Issue by phlegx** [elastic/apm-server#2982]
Hi there,

In all metric beats one can setup the default ILM in the yaml config i.e. like this:

```
setup:
    enabled: auto
    policy_name: default-metric-beats-ilm
```

I tried this same setting with APM server but it didn't work, so I assume it is not implemented. Would be nice if apm-server could offer the same settings. 

Best 
Martin

**Comment by simitt** [comment]
Hi @phlegx , thanks for the feature request. The supported configuration options for ILM are indeed different for APM Server than for other beats, and can be found within `apm-server.ilm.*`. 

You're right that at the moment one cannot configure ILM policies via the server. This feature is implemented already though and will be part of the 7.5 release. You can find more information at https://github.com/elastic/apm-server/issues/2240, as well as in the [upcoming documentation](https://www.elastic.co/guide/en/apm/server/7.5/ilm.html).

**Comment by simitt** [comment]
Until then, plase see how you can [manually configure ILM](https://www.elastic.co/guide/en/apm/server/current/manual-ilm-setup.html).

**Comment by phlegx** [comment]
Hi @simitt 

I now update the apm serve to `7.5.0` but it the policy does not seem to be applied. This is my confg, the ILM I have from your documetntation link. Do you see any problems with this?

```
apm-server:
  host: "0.0.0.0:8200"
  concurrent_requests: 5
  ilm:
    setup:
      enabled: auto
      overwrite: true
      require_policy: true
      templates:
        - event_type: "error"
          policy_name: "default-metric-beats-ilm"
        - event_type: "span"
          policy_name: "default-metric-beats-ilm"
        - event_type: "transaction"
          policy_name: "default-metric-beats-ilm"
        - event_type: "metric"
          policy_name: "default-metric-beats-ilm"

logging.level: info

setup:
  kibana:
    host: 'kibana:5601'

queue:
  mem:
    # Set queue size
    events: 4096

config:
  api_buffer_size: 1500

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
```

Also what I noticed is, that with the other beats the ILM configuration takes place in the `setup` section, whereas apm ILM config takes place in `apm-server` section:

See for example https://www.elastic.co/guide/en/beats/filebeat/current/ilm.html

Is there a reason why it is like that?

thanks!

**Comment by simitt** [comment]
Is my assumption right that `default-metric-beats-ilm` is already setup in ES and you only want to point your APM indices to use this policy? If so, then you should set `apm-server.setup.require_policy: false`, as this indicates whether or not the referenced policies need to be configured in the `apm-server.yml`. 

In this case your ILM config should look something like:
```
apm-server:
  ilm:
    enabled: "auto"
    setup:
      enabled: true
      overwrite: true
      require_policy: false
      mapping:
        - event_type: "error"
          policy_name: "default-metric-beats-ilm"
        - event_type: "span"
          policy_name: "default-metric-beats-ilm"
        - event_type: "transaction"
          policy_name: "default-metric-beats-ilm"
        - event_type: "metric"
          policy_name: "default-metric-beats-ilm"
```

There is a bug in one of the doc examples, using `templates` instead of `mappings`, we will fix that. 

APM Server creates multiple indices versus other beats create one index per beat. Therefore we needed some different behavior in creating templates to allow for different retention policy per index. To avoid confusion when applying different meanings to the same settings, we decided to introduce a dedicated `ILM` section for APM.

**Comment by simitt** [comment]
Created an issue to fix the docs #3043 .

@phlegx please let me know if that works for you, in which case we can close this issue now.

**Comment by phlegx** [comment]
Hi @simitt 

yes your assumption was right! Thanks a lot for the good explanation.

I can confirm that this setting works for me:

```
  ilm:
    setup:
      enabled: true
      overwrite: true
      require_policy: false
      mapping:
        - event_type: "error"
          policy_name: "default-metric-beats-ilm"
        - event_type: "span"
          policy_name: "default-metric-beats-ilm"
        - event_type: "transaction"
          policy_name: "default-metric-beats-ilm"
        - event_type: "metric"
          policy_name: "default-metric-beats-ilm"
```

In your example there is element `enabled` twice. Guess it is just a typo.
