### ISSUE TITLE
Enabling API Key without additional secret token breaks self instrumentation

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3051]
When using self instrumentation via the elastic go-apm-agent the agent can either talk to a remote server or to localhost via a in-process listener.
When the APM Server is configured to require a secret token, the agent uses the configured token for the server communication. With introducing API Key support the server requires a valid API Key if no additional secret token is configured. 

We can either require the user to configure a valid API Key within the APM Server instrumentation configuration and use that as soon as the agent supports API Keys or investigate if we can disable the API Key requirement for the loopback listener.

**Comment by axw** [comment]
IMO self-instrumentation should not require an API Key unless configured to send to another APM Server, and we should instead have the in-memory transport always auth'd for `PrivilegeAgentConfigRead` and `PrivilegeEventWrite`.

We would need to be careful not to have this spill over to the regular transport, but that should be taken care of by existing auth/system integration tests if we enable self-instrumentation by default.

**Comment by graphaelli** [comment]
investigate overlap with TLS configuration interop - TLS client auth might prevent self instrumentation currently.

**Comment by simitt** [comment]
Tested that self-instrumentation without configuring an API Key still works when the APM Server has API Key auth enabled. 
Used configuration:
```
apm-server:
  #secret_token:

  # Enable API key authorization by setting enabled to true. By default API key support is disabled.
  # Agents include a valid API key in the following format: Authorization: ApiKey <token>.
  # The key must be the base64 encoded representation of the API key's "id:key".
  api_key:
    enabled: true

  # Instrumentation support for the server's HTTP endpoints and event publisher.
  instrumentation:
    # Set to true to enable instrumentation of the APM Server itself.
    enabled: true

    # Environment in which the APM Server is running on (eg: staging, production, etc.)
    #environment: ""

    # Remote hosts to report instrumentation results to.
    #hosts:
    #  - http://remote-apm-server:8200

    # API Key for the remote APM Server(s).
    # If api_key is set then secret_token will be ignored.
    #api_key:

```

APM Server logs excerpt:
```
2020-01-23T13:32:23.530+0100	INFO	[request]	middleware/log_middleware.go:97	request accepted	{"request_id": "fecf92c4-834a-4d22-8f82-fe13bce340aa", "method": "POST", "URL": "/intake/v2/events", "content_length": -1, "remote_address": "pipe", "user-agent": "elasticapm-go/1.7.0 go/go1.13.6", "response_code": 202}
```

APM UI:
![Screenshot 2020-01-23 at 13 37 59](https://user-images.githubusercontent.com/5555349/72985155-9da71780-3de5-11ea-9f0e-7a3a0235241d.png)

Everything works as expected.
