### ISSUE TITLE
Strict config validation mode

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#3337]
Sometimes people set config in the wrong place, and then it's not obvious to them why the server isn't picking it up. Just recently I came across a situation where someone had set:

```yaml
apm-server:
  host: "0.0.0.0:8200"
    frontend:
      enabled: false
ilm:
  enabled: "true"
```

This won't work, because the `ilm` needs to be nested underneath `apm-server` (although - I wonder if that's the most logical place for it?)

Anyway, it would be helpful if the server (libbeat) had a strict config validation mode which would complain upon seeing unknown config keys. Extra points if it gave a suggested fix.
