### ISSUE TITLE
Add agent IP address to context

### ISSUE THREAD

**Issue by exekias** [elastic/apm-server#349]
It would be really useful to collect source host / IP address from agents on every request. Apart from having the info, this feature would allow `add_kubernetes_metadata` to match originating pod and enrich events with metadata from Kubernetes.

I've been playing with that idea and did this:

https://github.com/elastic/apm-server/compare/master...exekias:system-ip?expand=1

along with these settings:
```
processors:
- add_kubernetes_metadata:
    indexers:
      - ip_port:
    matchers:
      - fields:
          lookup_fields: ["context.system.ip"]
```

so far it works.
