### ISSUE TITLE
[docs] Add required privileges for using API Keys

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#3566]
Current [API Key docs](https://www.elastic.co/guide/en/apm/server/current/api-key.html#create-api-key-privileges) and [API Key CLI docs](https://www.elastic.co/guide/en/apm/server/current/command-line-options.html#apikey-command) mention application privileges and briefly the `manage_ai_key` cluster privilege, but they are not listed in [Grant users access to secured resources](https://www.elastic.co/guide/en/apm/server/7.6/feature-roles.html), which summarizes all other privileges that are necessary. 

We should add the privileges for the following use case:

Creating API Keys via the CLI tool requires 
* `manage_api_key` privilege on `cluster` 
* application privileges when the user creating the API Keys is not a `superuser`: 
```
  applications:
    - application: 'apm'
      privileges: ['sourcemap:write', 'event:write', 'config_agent:read']
      resources: '*'
```

cc @bmorelli25
