### ISSUE TITLE
Ensure continuity of distributed traces across OpenTelemetry/Elastic agents

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#3863]
This is an issue to test distributed tracing using a mix of OpenTelemetry SDKs and Elastic APM agents will work.

**Comment by jalvz** [comment]
This is not working as I expect, but very possibly I am doing something wrong...

1. `git clone git@github.com:open-telemetry/opentelemetry-collector-contrib.git`
2. `export OTEL_AGENT_ENDPOINT=0.0.0.0:55678`
3. `make otelcontribcol`

4. `bin/otelcontribcol_linux_amd64 --config otel-local-config.yaml`
`otel-local-config.yaml` is as follows:
```yaml
   receivers:
     opencensus:
       endpoint: 0.0.0.0:55678

   processors:
     batch:
     queued_retry:

   exporters:
     logging:
     elastic:
        apm_server_url: "http://localhost:8200"        

   service:
     pipelines:
       traces:
         receivers: [opencensus]
         processors: [batch, queued_retry]
         exporters: [logging, elastic]
```

5. run the Elastic stack

6. run service running OT agent 
```go

import (
	"context"
	"fmt"
	"log"
	"math/rand"
	"net/http"
	"os"
	"time"
	"contrib.go.opencensus.io/exporter/ocagent"
	"go.opencensus.io/trace"
)

func main() {
	ocAgentAddr, ok := os.LookupEnv("OTEL_AGENT_ENDPOINT")
	if !ok {
		ocAgentAddr = ocagent.DefaultAgentHost + ":" + string(ocagent.DefaultAgentPort)
	}
	oce, err := ocagent.NewExporter(
		ocagent.WithAddress(ocAgentAddr),
		ocagent.WithInsecure(),
		ocagent.WithServiceName(fmt.Sprintf("example-go-%d", os.Getpid())))
	if err != nil {
		log.Fatalf("Failed to create ocagent-exporter: %v", err)
	}
	trace.RegisterExporter(oce)
	trace.ApplyConfig(trace.Config{
		DefaultSampler: trace.AlwaysSample(),
	})

	http.HandleFunc("/", ot)
	http.ListenAndServe(":3003", nil)
}

func ot() func(w http.ResponseWriter, req *http.Request) {
	rng := rand.New(rand.NewSource(time.Now().UnixNano()))
	for i := 0; i < 10; i++ {
		ctx, span := trace.StartSpan(context.Background(), "Foo")
		var sleep int64
		switch modulus := time.Now().Unix() % 5; modulus {
		case 0:
			sleep = rng.Int63n(17001)
		case 1:
			sleep = rng.Int63n(8007)
		case 2:
			sleep = rng.Int63n(917)
		case 3:
			sleep = rng.Int63n(87)
		case 4:
			sleep = rng.Int63n(1173)
		}
		time.Sleep(time.Duration(sleep) * time.Millisecond)
	}
}
```
7. run service instrumented with Elastic agent
```go

import (
	"context"
	"fmt"
	"net/http"
	"go.elastic.co/apm"
	"go.elastic.co/apm/module/apmhttp"
	"time"
)

func main() {
	tracer := apm.DefaultTracer
	client := apmhttp.WrapClient(http.DefaultClient)
	for {
		tx := tracer.StartTransaction("GET /", "request")
		req, err := http.NewRequest("GET", "http://localhost:3003", nil)
		if err != nil {
			fmt.Println(err)
			tracer.NewError(err).Send()
		}
		_, err = client.Do(req.WithContext(context.Background()))
		tx.End()
		if err != nil {
			fmt.Println(err)
			tracer.NewError(err).Send()
		}
		time.Sleep(time.Second)
	}
}
```

Outcome:

![image](https://user-images.githubusercontent.com/3432712/84659671-11be9500-af18-11ea-9f4c-a109b23faa99.png)

![image](https://user-images.githubusercontent.com/3432712/84659905-67933d00-af18-11ea-999c-fefd6d4ca59d.png)


This is the Elastic Agent initiating the trace, but doing it the other way around is the same.
