### ISSUE TITLE
 Support to create index for each service

### ISSUE THREAD

**Issue by seven-yu** [elastic/apm-server#4025]
Apm creates a global index for all services by default：
apm-%{[beat.version]}-%{+yyyy.MM.dd}

Considering the management of ES storage capacity, I need to analyze the data growth trend of some major services, not the total amount of all services

Is there a way to achieve this demand？

**Comment by axw** [comment]
Hello @AEGEGE! We use the Github repository for verified bug reports, pull requests, apm-server specific feature requests, etc.

For questions such as yours, please head over to our official [Discuss](https://discuss.elastic.co/c/apm) forum. You will reach a wider audience, get help from the broader community, and maybe learn how others solved similar problems.

To get you started, please see https://www.elastic.co/guide/en/apm/server/current/elasticsearch-output.html#indices-option-es

**Comment by axw** [comment]
(Apologies for the ping AEGEGE, copy-and-paste fail.)

**Comment by Baklap4** [comment]
Upon saving the below snippet in the cloud console we get this error message.. What rules are currently supported?

snippet:
```
output.elasticsearch:
  indices:
    - index: 'apm-%{[observer.version]}-%{[kubernetes.labels.app]}-%{+yyyy.MM}'
      when:
        not:
          or:
            - equals:
                kubernetes.namespace: botkube
            - equals:
                kubernetes.namespace: default
```
![image](https://user-images.githubusercontent.com/3918517/89158887-01698480-d56f-11ea-8403-5b13e2f9a75b.png)
