### ISSUE TITLE
Document how to use environment variables to configure APM server

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-server#440]
APM Server doesn't read environment variables directly, but you can use environment variables to configure APM Server by specifying them on the command line. We need to document examples on how to configure the APM Server through environment variables, for example for docker-compose:

```yml
version: "2.1"
services:
  apm-server:
    image: docker.elastic.co/apm/apm-server:${STACK_VERSION:-6.1.1}
    environment:
      - ESHOST="http://differentHost:9200"
    command: apm-server -e -E output.elasticsearch.hosts=$${ESHOST}"
```
