### ISSUE TITLE
Visualize JVM health indicators collected by the OpenTelemetry Java Agent

### ISSUE THREAD

**Issue by cyrille-leclerc** [elastic/apm-server#4919]
**APM Server version** (`apm-server version`):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

https://github.com/cyrille-leclerc/my-shopping-cart/tree/39d22e715d96e15d5540ea28eca007de9d3edab8

### JVM Runtime Metrics reported by the OpenTelemetry Collector Prometheus Exporter

```
# HELP runtime_jvm_gc_collection Time spent in a given JVM garbage collector in milliseconds.
# TYPE runtime_jvm_gc_collection counter
runtime_jvm_gc_collection{gc="G1 Old Generation"} 0
runtime_jvm_gc_collection{gc="G1 Young Generation"} 22
# HELP runtime_jvm_memory_area Bytes of a given JVM memory area.
# TYPE runtime_jvm_memory_area counter
runtime_jvm_memory_area{area="heap",type="committed"} 5.6623104e+07
runtime_jvm_memory_area{area="heap",type="max"} 4.294967296e+09
runtime_jvm_memory_area{area="heap",type="used"} 1.4552776e+07
runtime_jvm_memory_area{area="non_heap",type="committed"} 4.1222144e+07
runtime_jvm_memory_area{area="non_heap",type="used"} 3.7732072e+07
# HELP runtime_jvm_memory_pool Bytes of a given JVM memory pool.
# TYPE runtime_jvm_memory_pool counter
runtime_jvm_memory_pool{pool="CodeHeap 'non-nmethods'",type="committed"} 2.555904e+06
runtime_jvm_memory_pool{pool="CodeHeap 'non-nmethods'",type="max"} 5.840896e+06
runtime_jvm_memory_pool{pool="CodeHeap 'non-nmethods'",type="used"} 1.288832e+06
runtime_jvm_memory_pool{pool="CodeHeap 'non-profiled nmethods'",type="committed"} 2.555904e+06
runtime_jvm_memory_pool{pool="CodeHeap 'non-profiled nmethods'",type="max"} 1.22908672e+08
runtime_jvm_memory_pool{pool="CodeHeap 'non-profiled nmethods'",type="used"} 1.288448e+06
runtime_jvm_memory_pool{pool="CodeHeap 'profiled nmethods'",type="committed"} 6.750208e+06
runtime_jvm_memory_pool{pool="CodeHeap 'profiled nmethods'",type="max"} 1.22908672e+08
runtime_jvm_memory_pool{pool="CodeHeap 'profiled nmethods'",type="used"} 6.70784e+06
runtime_jvm_memory_pool{pool="Compressed Class Space",type="committed"} 3.407872e+06
runtime_jvm_memory_pool{pool="Compressed Class Space",type="max"} 1.073741824e+09
runtime_jvm_memory_pool{pool="Compressed Class Space",type="used"} 3.266448e+06
runtime_jvm_memory_pool{pool="G1 Eden Space",type="committed"} 2.9360128e+07
runtime_jvm_memory_pool{pool="G1 Eden Space",type="used"} 2.097152e+06
runtime_jvm_memory_pool{pool="G1 Old Gen",type="committed"} 2.5165824e+07
runtime_jvm_memory_pool{pool="G1 Old Gen",type="max"} 4.294967296e+09
runtime_jvm_memory_pool{pool="G1 Old Gen",type="used"} 1.0550784e+07
runtime_jvm_memory_pool{pool="G1 Survivor Space",type="committed"} 2.097152e+06
runtime_jvm_memory_pool{pool="G1 Survivor Space",type="used"} 1.90484e+06
runtime_jvm_memory_pool{pool="Metaspace",type="committed"} 2.5952256e+07
runtime_jvm_memory_pool{pool="Metaspace",type="used"} 2.5180024e+07
```
### Sample Elastic APM Metrics document for `runtime.jvm.memory.area{area="non_heap",type="used"}`

```yaml
{
  "_index": "apm-7.12.0-metric-000001",
  "_type": "_doc",
  "_id": "ug4U_ncBlMla0ZqF00Vo",
  "_version": 1,
  "_score": null,
  "_source": {
    "agent": {
      "name": "opentelemetry/java",
      "version": "0.17.0"
    },
    "process": {
      "pid": 4990
    },
    "runtime": {
      "jvm": {
        "memory": {
          "area": 37609512
        }
      }
    },
    "processor": {
      "name": "metric",
      "event": "metric"
    },
    "labels": {
      "process_runtime_description": "AdoptOpenJDK OpenJDK 64-Bit Server VM 15.0.2+7",
      "area": "non_heap",
      "os_type": "DARWIN",
      "process_executable_path": "/Library/Java/JavaVirtualMachines/adoptopenjdk-15.jdk/Contents/Home:bin:java",
      "process_runtime_name": "OpenJDK Runtime Environment",
      "os_description": "Mac OS X 10.16",
      "service_namespace": "com-shoppingcart",
      "process_command_line": "/Library/Java/JavaVirtualMachines/adoptopenjdk-15.jdk/Contents/Home:bin:java -javaagent:./../.otel/opentelemetry-javaagent-all-0.17.0.jar -Dio.opentelemetry.auto.slf4j.simpleLogger.defaultLogLevel=info",
      "type": "used",
      "process_runtime_version": "15.0.2+7",
      "telemetry_auto_version": "0.17.0"
    },
    "observer": {
      "hostname": "MacBook-Pro.localdomain",
      "id": "f9c7166f-0f12-4fc4-8c1d-3c137d9b382a",
      "type": "apm-server",
      "ephemeral_id": "6e8d9a14-4392-49f5-b73a-e2df869bfc33",
      "version": "7.12.0",
      "version_major": 7
    },
    "@timestamp": "2021-03-04T16:31:52.663Z",
    "ecs": {
      "version": "1.6.0"
    },
    "service": {
      "environment": "staging",
      "name": "monitor",
      "language": {
        "name": "java"
      },
      "version": "1.0-SNAPSHOT"
    },
    "event": {
      "ingested": "2021-03-04T16:31:53.702349Z"
    }
  },
  "fields": {
    "event.ingested": [
      "2021-03-04T16:31:53.702Z"
    ],
    "@timestamp": [
      "2021-03-04T16:31:52.663Z"
    ]
  },
  "sort": [
    1614875512663
  ]
}
```

**Comment by axw** [comment]
@cyrille-leclerc I'm relabelling this as "enhancement", since we previously never intended to translate metrics. I think it's reasonable to do, but I haven't yet checked feasibility.

**Comment by graphaelli** [comment]
@axw @sqren @felixbarny Any thoughts on doing this in apm server versus handling elsewhere, including ingest pipeline or UI?  I see the benefit handling via apm server but also concerned about putting that responsibility there.  The benefit of ingest pipeline is that it could be updated out of cycle with the stack, eventually via a simple package update.  I think UI suffers form the same complexity as putting this in server but interested in your thoughts.

**Comment by axw** [comment]
@graphaelli IMO it's a job for our ingest pipeline. The server doesn't need to perform any computation on the metrics, so there's no real benefit to doing it there. I expect doing it in the ingest pipeline would help keep the UI code cleaner and more efficient, but @sqren would know better.

I'd like to pick on this:

> The benefit of ingest pipeline is that it could be updated out of cycle with the stack, eventually via a simple package update.

I'd rather like to think of the package as just another part of each release, and keep them in sync. IMO, ideally the package would be bundled with Kibana, just like we bundle APM Server with Elastic Agent. That way when we upgrade Kibana to X.Y.Z, we get exactly version X.Y.Z of the package installed, and the APM UI code can assume things about the data streams installed.

See also https://github.com/elastic/kibana/issues/93194#issue-819918304. Maybe let's continue discussing there?

**Comment by axw** [comment]
One caveat about the pipeline approach: metric labels get combined with other attributes, as can be seen in the example in the description. This muddies the waters a little bit about where exactly the labels (which also need to be translated) come from -- are they metric dimensions, or are they just some attributes of the application? This is a bit clearer in the APM Server code. Not a big deal though.

**Comment by felixbarny** [comment]
Another consideration is whether we should store the metrics in the original format, the translated format, or both.

* Store only original format
  * Changes in UI needed to fall back to OTel metrics
  * 👍 No duplication
  * 👍 We store the metrics as documented by the OTel agent
  * 👎  No custom dashboards for both OTel and Elastic APM services
* Store both the original and the translated format
  * Transform in APM Server or ingest pipeline, no changes in UI needed
  * 👍 We store the metrics as documented by the OTel agent
  * 👍 Custom dashboards for both OTel and Elastic APM services
  * 👎 Duplication of metrics
* Store only the translated format
  * Transform in APM Server or ingest pipeline, no changes in UI needed
  * 👍 No duplication
  * 👍 Custom dashboards for both OTel and Elastic APM services
  * 👎 May be confusing for OTel users (why is the metric that OTel documents not present?)

I think we should rule out storing only in the translated format as it seems like a rather intrusive approach with the potential for confusion. It's also not a model that works well going forward. What if we want to translate more metrics? It could be considered a breaking change.

I don't have a strong opinion about options 1 and 2, both have their pros and cons, but I gravitate towards just storing the metrics in the original format and doing a fallback in the UI for OTel.

**Comment by sqren** [comment]
I don't have any strong opinions on this. I'm learning towards option 2 to keep things consistent but if needed this can be handled by the ui.

**Comment by axw** [comment]
Good point about surprising users by changing metric names.

My preference would be option 2, store both by default. We can always provide guidance to users to add another ingest processor to drop duplicates if they don't want or need them.

**Comment by cyrille-leclerc** [comment]
On the original format, is it desired to have `area="non_heap"` and `type="used"` handled as `labels` the same way we handle `process_executable_path` or `os_description`?

Maybe the improvement is to have full ECS mapping for more attributes that are today handled as `labels`.

Reference in Prometheus:

```
runtime_jvm_memory_area{area="non_heap",type="used"} 3.7732072e+07
```

**Comment by axw** [comment]
@cyrille-leclerc I think it's desirable to have `area="non_heap"` and `type="used"` as labels, but not for `process_executable_path` etc. to be labels. The latter _should_ be translated to ECS (https://github.com/elastic/apm-server/issues/4714), we just haven't handled them yet. We record unhandled attributes as labels so they're still available to users as a fallback.

**Comment by cyrille-leclerc** [comment]
@axw thanks, do you know how metricbeat handles attributes when collecting prometheus metrics? do they use the `label`block?

**Comment by felixbarny** [comment]
Yes, I also like their guidelines. But it almost seems like they violate their own rules here :)

**Comment by axw** [comment]
> @axw thanks, this plans looks good to me. I see that #4714 is marked in Zube as "backlog" rather than "ready". What's needed to move #4714 forward?

A 25th hour in each day would be a good start ;)

For 7.13 I think we can manage to translate the attributes for which there are existing analogues in our agents, e.g. `process_executable_path`, `process_runtime_name`, `process_runtime_version`. Other attributes may have to wait. Let's discuss further on that issue if needed.

**Comment by cyrille-leclerc** [comment]
> A 25th hour in each day would be a good start ;)

@axw I wanted to understand if additional specification work was needed :-)

> For 7.13 I think we can manage to translate the attributes for which there are existing analogues in our agents, e.g. `process_executable_path`, `process_runtime_name`, `process_runtime_version`. Other attributes may have to wait. Let's discuss further on that issue if needed.

Does it mean that we/I should prepare this mapping?
Should we align with @urso to have the same mapping used in the logs exporter for Elasticsearch and in the OTLP intake we have for traces and metrics?

**Comment by axw** [comment]
@cyrille-leclerc I've responded on #4714.

**Comment by axw** [comment]
@felixbarny @sqren and I just discussed this, and we will go with the duplicating ingest pipeline approach for now.

**Comment by axw** [comment]
I could do with some help defining the mapping.

The OpenTelemetry Java metrics code is at https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/runtime-metrics/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics

Our agent's metrics are documented at https://www.elastic.co/guide/en/apm/agent/java/current/metrics.html#metrics-jvm

Here's the mapping I've got so far, in an ingest pipeline:

```yaml
apm_opentelemetry_metrics:                                                                               
  description: Populate Elastic APM metric fields from well-known OpenTelemetry metric counterparts      
  processors:                                                                                            
  - set:                                                                                                 
      # Copy `runtime.jvm.memory.area` (OpenTelemetry) to `jvm.memory.{area}.{type}` (Elastic APM).      
      field: jvm.memory.{{labels.area}}.{{labels.type}}                                                  
      copy_from: runtime.jvm.memory.area                                                                 
      if: ctx.runtime?.jvm?.memory?.area != null && ctx.labels?.area != null && ctx.labels?.type != null 
  - set:                                                                                                 
      # Copy `runtime.jvm.gc.collection` (OpenTelemetry) to `jvm.gc.time` (Elastic APM).                 
      # Both are defined in milliseconds.                                                                
      field: jvm.gc.time                                                                                 
      copy_from: runtime.jvm.gc.collection                                                               
      if: ctx.runtime?.jvm?.gc?.collection != null && ctx.labels?.gc != null                             
  - set:                                                                                                 
      # Copy `labels.gc` (OpenTelemetry) to `labels.name` (Elastic APM), for jvm.gc.time.                
      field: labels.name                                                                                 
      copy_from: labels.gc                                                                               
      override: false # don't replace existing labels.name field, if any                                 
      if: ctx.labels?.gc != null                                                                         
```

A couple of discrepancies:
 - There does not appear to be any OpenTelemetry metrics corresponding to our `jvm.gc.count` or `jvm.gc.alloc`.
 - There does not appear to be any Elastic APM metrics corresponding to OpenTelemetry's `runtime.jvm.memory.pool`
