### ISSUE TITLE
Feature: enable agent config to be defined in APM Server config

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#4929]
Currently agent config can be defined at the agent level, or centrally in Kibana. In the latter case, agents poll APM Server which then queries Kibana for config.

As we migrate the server to being Fleet managed, we have an opportunity to remove the direct connection from APM Server to Kibana: instead of having APM Server query Kibana, we could instead push agent config down to APM Server via a Fleet policy update.

To enable this, we will need to make it possible to define agent config in APM Server's config (e.g. apm-server.yml). e.g.

```yaml
apm-server:
    agent_config:
        - service.name: opbeans-go
          service.environment: production
          settings:
              transaction_sample_rate: 0.1
```

When managed by Fleet this config would change dynamically. Currently we restart all of the APM Server's internals (HTTP listener, sampling, aggregation, etc.) every time config changes. We should not do this when only agent config changes (and probably for many other things too).
