### ISSUE TITLE
Introduce configuration for specifying service-specific source maps

### ISSUE THREAD

**Issue by axw** [elastic/apm-server#5002]
As part of the move to Fleet we will need to move away from fetching source maps directly from (and indexing source maps into) Elasticsearch, as the privileges APM Server is given does not cover this. Instead, source maps should be uploaded to Kibana, stored as a Fleet Artifact, with references to Fleet Artifact download URLs pushed down to APM Server via the server's policy.

In order to make the above possible, we will add configuration to APM Server to specify zero or more source maps, including:
 - service name
 - service version
 - bundle filepath
 - source map URL (typically a Fleet Server artifact download URL)

For example:

```yaml
apm-server:
  rum:
    source_mapping:
      source_maps:
      - service.name: opbeans-rum
        service.version: 1.2.3
        bundle.filepath: /test/e2e/general-usecase/bundle.js.map
        sourcemap.url: http://somewhere.com/bundle.js.map
```

The server will fetch and cache these like today: fetch on first access, cache in memory with an expiration time. We might make improvements to caching later, but that can be done separately. If the list of source maps is dynamically updated, then the cache will be invalidated for (service name, service version, bundle filepath) tuples that are added, changed, or removed.

Configuring a list of source maps will disable fetching source maps from Elasticsearch. It will be an error to specify Elasticsearch configuration under `apm-server.rum.source_mapping` if the `source_maps` property is non-null.

Fleet Server requires auth for fetching artifacts. If a source map URL points to Fleet Server, then APM Server must pass its Fleet API access key in download requests.
