### ISSUE TITLE
anonymous auth not respected for ios agent

### ISSUE THREAD

**Issue by simitt** [elastic/apm-server#6095]
## Expected behavior
When enabling APM Server with a secret token and enabling anonymous auth, requests from the [iOS agent](https://github.com/elastic/apm-agent-ios) should not require having a secret token set when the `apm-server.auth.anonymous.allow_agent` config contains `iOS/swift`. 

## Observed behavior
Requests from an iOS agent where no `secret-token` is configured fail with following error
```
{"log.level":"error","@timestamp":"2021-08-31T14:59:06.897+0200","log.logger":"beater.grpc","log.origin":{"file.name":"interceptors/logging.go","file.line":63},"message":"{error 26 0  rpc error: code = Unauthenticated desc = authentication failed}","service.name":"apm-server","source.address":"127.0.0.1","grpc.request.method":"/opentelemetry.proto.collector.trace.v1.TraceService/Export","event.duration":24098,"grpc.response.status_code":"Unauthenticated","error.message":"authentication failed","ecs.version":"1.6.0"}
```

## How to reproduce
0. set `apm-server.yml` config to:
```
apm-server:
  auth:
    api_key:
      enabled: true
    secret_token: "1234"
    anonymous:
      enabled: true
      allow_agent: [iOS/swift, rum-js, js-base]
```
1. send requests from the iOS agent, specifying a `secret-token` in the iOS agent and observe that the ingestion works as expected. 
2. send requests from the iOS agent, not setting a `secret-token` in the iOS agent and observe that the ingestion fails
