### ISSUE TITLE
APM returns a 404 when attempting to send OTLP data

### ISSUE THREAD

**Issue by MeijerM1** [elastic/apm-server#6267]
**APM Server version** (`7.15.0`):

**Description of the problem including expected versus actual behavior**:
The APM server is returning a 404 error on the following url `/opentelemetry.proto.collector.trace.v1.TraceService/Export` when attempting to send OTLP data from an application.

Complete error log:
```
{"log.level":"error","@timestamp":"2021-09-30T13:35:42.705Z","log.logger":"request","log.origin":{"file.name":"middleware/log_middleware.go","file.line":60},"message":"404 page not found","service.name":"apm-server","url.original":"/opentelemetry.proto.collector.trace.v1.TraceService/Export","http.request.method":"POST","user_agent.original":"grpc-dotnet/2.32.0.0","source.address":"10.100.16.123","http.request.id":"e8315ebe-0877-42cd-bb98-93d7d9385963","event.duration":105601,"http.response.status_code":404,"error.message":"404 page not found","ecs.version":"1.6.0"}
```

**Steps to reproduce**:
 1. Instrument a .net core 3.1 application using the following OpenTelemetry packages
```
<PackageReference Include="OpenTelemetry" Version="1.1.0" />
<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.1.0" />
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc7" />
<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc7" />
<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc7" />
```
 2. Add the following configuration in the .net core app:
```
services.AddOpenTelemetryTracing((builder) => builder
                .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("MyApplication"))
                .AddAspNetCoreInstrumentation()
                .AddHttpClientInstrumentation(options =>
                {
                    options.SetHttpFlavor = true;
                })
                .AddOtlpExporter(options =>
                {
                    options.Endpoint = new Uri("http:/my-apm-server.my-namespace.svc:8200/);
                    options.Headers = "authorization=Bearer SecretToken";
                })
```
 3. Run APM on Kubernetes with the following configuration:
```
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-test
  namespace: logging
spec:
  version: 7.15.0
  count: 1
  kibanaRef:
    name: my-kibana
  elasticsearchRef:
    name: my-elastic
  secureSettings:
  - secretName: apm-server-test-apm-token
  http:
    tls: 
      selfSignedCertificate:
        disabled: true
  config:
    output:
      elasticsearch:
        hosts: ["http://my-elastic.my-namespace.svc:9200"]
        username: myUsername
        password: myPassword
```

**Other relevant information**
```
ECK Version: 1.7.1
Kubernetes: 1.21
``` 

**Provide logs (if relevant)**:
