### ISSUE TITLE
Automatically enable `auth.anonymous` when `rum.enabled: true`

### ISSUE THREAD

**Issue by marclop** [elastic/apm-server#6570]
## Description

Prior to `8.0.0`, users could enable RUM and allow their `apm-server` to accept certain service names only with the following configuration:

```yaml
apm-server:
  rum:
    enabled: true
    allow_service_names: [serviceA]
```

`apm-server.rum.allow_service_names ` is deprecated in `8.0.0` in favor of `apm-server.auth.anonymous.allow_service`, with the caveat that they also need to set `apm-server.auth.anonymous.enabled: true`:

```yaml
apm-server:
  auth:
    anonymous:
      enabled: true
      allow_service: [serviceA]
  rum:
    enabled: true
```

This may not be obvious (it wasn't for me) and could cause confusion for our RUM users.

## Proposed enhancement

We should change the configuration parsing logic to set `apm-server.auth.anonymous.enabled: true` when `apm-server.rum.enabled: true`, unless `apm-server.auth.anonymous.enabled` is set.

## Related issues

Discovered while working on https://github.com/elastic/apm-server/pull/6560
