### ISSUE TITLE
Monitoring data is not indexed in ES 

### ISSUE THREAD

**Issue by bryce-b** [elastic/apm-server#6581]
**APM Server version** (`apm-server version`): v7.16.0-SNAPSHOT

**Description of the problem including expected versus actual behavior**:

Data captured in `.monitoring-beats*` indices under `beats_stats.metrics.apm-server.sampling.*` is not indexed and can not be queried in the Console or charts.  

**Steps to reproduce**:

 1. enable tail-based sampling in the apm-server
e.g.:
```
apm-server:
  data_streams:
    enabled: true
  sampling:
    keep_unsampled: false
    tail:
      enabled: true
      ttl: 30s
      interval: 1s
      policies: 
        - sample_rate: 0.1 

```
 2. enable stack monitoring
 3. try to query beats_stats.metrics.apm-server.sampling.*
e.g.: 
```
GET .monitoring-beats-7-2021.11.11/_search
{
  "query": {
    "bool": {
      "filter": [
        { 
          "exists": {
            "field": "beats_stats.metrics.apm-server.sampling"
          }
        }
      ]
    }
  }
}
```

**Provide logs (if relevant)**:
