### ISSUE TITLE
[8.0] Trouble connecting APM to Elasticsearch 

### ISSUE THREAD

**Issue by liza-mae** [elastic/apm-server#6619]
Version: 8.0, 8.1

I noticed a recent change that now apm server is not connecting to elasticsearch.  I don't see any error in the log, so maybe it is a new configuration that I am missing.  Can someone help verify if it is a bug or not? 

I am using the default apm-server.yml with just some added parameters for security, nothing else modified in the default configuration.

```
output.elasticsearch:
  username: elastic
  password: changeme
  protocol: https
  hosts: ["10.0.2.15:9200"]
  enabled: true
  ssl.certificate_authorities: /home/vagrant/apm-server-8.0.0-SNAPSHOT-linux-x86_64/ca/ca.crt
  ssl.certificate: /home/vagrant/apm-server-8.0.0-SNAPSHOT-linux-x86_64/node/node.crt
  ssl.key: /home/vagrant/apm-server-8.0.0-SNAPSHOT-linux-x86_64/node/node.key

setup.kibana:
  host: "10.0.2.15:5601"
  protocol: https
  ssl.certificate_authorities: /home/vagrant/apm-server-8.0.0-SNAPSHOT-linux-x86_64/ca/ca.crt
  ssl.certificate: /home/vagrant/apm-server-8.0.0-SNAPSHOT-linux-x86_64/node/node.crt
  ssl.key: /home/vagrant/apm-server-8.0.0-SNAPSHOT-linux-x86_64/node/node.key
```

I am looking for a message similar to the below taken from 7.16, in the log, but it is missing, no errors:
```
{"log.level":"info","@timestamp":"2021-11-15T13:22:10.214Z","log.logger":"publisher_pipeline_output","log.origin":{"file.name":"pipeline/output.go","file.line":143},"message":"Connecting to backoff(elasticsearch(https://10.0.2.15:9200))","service.name":"apm-server","ecs.version":"1.6.0"}
```
