### ISSUE TITLE
Defining apm-server.sampling.tail.interval causes throughput to cease

### ISSUE THREAD

**Issue by bryce-b** [elastic/apm-server#6638]
**APM Server version** (`apm-server version`): 7.16.0-SNAPSHOT

<br class="Apple-interchange-newline">

**Description of the problem including expected versus actual behavior**:
The issue appears when `tail.interval` is introduced in the configuration yaml.  The documentation describes using a flush interval no greater than half the duration of `tail.ttl`. Following this instruction, or setting any other value to `tail.interval` results in all throughput of apm server to cease.

**Steps to reproduce**:
Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

 1. Running on cloud
 2. sending data w/ apm-integration-testing
 3. apply the following configuration:
```
apm-server:
  data_streams:
    enabled: true
  sampling:
    keep_unsampled: false
    tail:
      enabled: true
      ttl: 30s
      interval: 15s
      policies: 
        - sample_rate: 0.1 
```
