### ISSUE TITLE
ES search rate very high when TBS enabled

### ISSUE THREAD

**Issue by bryce-b** [elastic/apm-server#6639]
**APM Server version** (`apm-server version`): 7.16.0-SNAPSHOT

**Description of the problem including expected versus actual behavior**:
When Tail-based sampling is enabled, ES search rate doubles
<img width="617" alt="Screen Shot 2021-11-16 at 9 59 07 AM" src="https://user-images.githubusercontent.com/75274611/142040004-fbf5e774-aa20-4d50-8e8f-934e95271e1f.png">
In the above screencap you can see when TBS is enabled at 21:30

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

 1. start cloud deployment
 2. apply APM integrations to deployment
 3. generate data w/ apm_integration_testing
4. apply configuration to APM Server: 
```
apm-server:
  data_streams:
    enabled: true
  sampling:
    keep_unsampled: false
    tail:
      enabled: true
	 policies:
	        - sample_rate: 0.1
```
