### ISSUE TITLE
Multiple service policies result in unusual sample rates

### ISSUE THREAD

**Issue by bryce-b** [elastic/apm-server#6640]
**APM Server version** (`apm-server version`): 7.16.0-SNAPSHOT

**Description of the problem including expected versus actual behavior**:
In testing, I used multiple tail-based sampling policies designed to apply unique sample rates to specific services. I used a comparison between the `request` transaction metrics count vs the `request` transaction traces captured to determine the actual sample rate. useful dashboard for comparison is found here: https://github.com/bryce-b/apm-server/blob/tbs-metrics/cmd/TBS/tbs_charts_3.2.ndjson

Here is the policies used in testing:
```
apm-server:
 sampling:
   keep_unsampled: false
   tail:
     enabled: true
   policies: 
        - service:
          name: "opbeans-java"
          sample_rate: 0.5
        - service:
          name: "opbeans-python"
          sample_rate: 0.2
        - service:
          name: "opbeans-ruby"
          sample_rate: 0.8
        - service:
          name: "opbeans-go"
          sample_rate: 0.6
        - sample_rate: 0.1
```

<img width="693" alt="Screen Shot 2021-11-16 at 10 38 39 AM" src="https://user-images.githubusercontent.com/75274611/142045596-88e1c46b-c328-47c9-ab89-9cc2fecdceae.png">

In testing, each service had some drift from the expected sample rate, which isn't unexpected, but the sample rate for opbeans-ruby is drastically different from the expected sample rate. 

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including server configuration, agent(s) used, etc.  The easier you make it
for us to reproduce it, the more likely that somebody will take the time to
look at it.

 1. start cloud deployment
 2. apply apm integration to deployment
 3. start apm-integration-testing for traffic
 4. apply apm-server config described above

**Provide logs (if relevant)**:
