### ISSUE TITLE
Failure to ingest OpenTelemetry metrics when one of them is `NaN`

### ISSUE THREAD

**Issue by cyrille-leclerc** [elastic/apm-server#6641]
**APM Server version** (`apm-server version`): 7.15.1

**Description of the problem including expected versus actual behavior**:

Failure to ingest OpenTelemetry metrics when one of them is `NaN` reporting the error message `"failed to perform any bulk index operations: unsupported float value: NaN"`

**Steps to reproduce**:

* Setup an OpenTelemetry Collector with
   * A Prometheus Receiver 
   *  An OTLP exporter toward Elastic APM Server 7.15.1
   * A Prometheus exporter for debugging purpose

<details>
<summary>opentelemetry-collector.yaml</summary>

```
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 1m
        scrape_timeout: 30s
        
      scrape_configs:
      
      - job_name: "kstream metrics"
        static_configs:
        - targets: ["kstream-service:9999"]
        relabel_configs:
          - source_labels: [__address__]
            target_label: hostname
            regex: '([^:]+)(:[0-9]+)?'
            replacement: '${1}'

exporters:
  otlp:
    endpoint: "http://apm-server:8200"
    insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [otlp, prometheus]
```

</details>

* Collect some Nan metrics via an OpenTelemetry Collector Prometheus receiver
* Verify on the OpenTelemetry Collector Prometheus exporter that some metric values are NaN
    ```
    # HELP kafka_streams_stream_task_metrics_active_process_ratio The fraction of time the thread spent on processing this task among all assigned active tasks (kafka.streams<type=stream-task-metrics, thread-id=streams-avro-to-jsonf96bb991-c1ca-44d2-b452-8d3216c23dfa-c1b72fd5-0129-49b8-a0d5-f1ff51b81e1c-StreamThread-1, task-id=0_0><>active-process-ratio)
    # TYPE kafka_streams_stream_task_metrics_active_process_ratio gauge
    kafka_streams_stream_task_metrics_active_process_ratio{task_id="0_0",thread_id="streams-avro-to-jsonf96bb991-c1ca-44d2-b452-8d3216c23dfa-c1b72fd5-0129-49b8-a0d5-f1ff51b81e1c-StreamThread-1"} NaN
    ```
* Verify in APM Server logs the messages 
   ```json
   {
      "log.level":"error",
      "@timestamp":"2021-11-16T20:52:22.882Z",
      "log.logger":"elasticsearch",
      "log.origin":{
         "file.name":"elasticsearch/client.go",
         "file.line":224
      },
      "message":"failed to perform any bulk index operations: unsupported float value: NaN",
      "service.name":"apm-server",
      "ecs.version":"1.6.0"
   }
   ```
* Verify in the index `apm-*-metric`, the OpenTelemetry metrics are missing

Demo application facing the problem https://github.com/chuck-confluent/kafka-distributed-tracing

cc @chuck-confluent
