### ISSUE TITLE
Investigate auto-setting `GOMAXPROCS`

### ISSUE THREAD

**Issue by marclop** [elastic/apm-server#7967]
## Problem statement

We are currently not setting `GOMAXPROCS` on ESS / ECE or deriving the value from docker container limits. This is normally not an issue except when APM Server is run on a containerized environment, which results in the `GOMAXPROCS` being set to the total number of CPUs for that machine.

On CPU intensive programs like the APM Server, this issue is worsened when container CFS quotas are used to limit the number of resources that docker containers have access to, which is something that we do in ESS / ECE. This seems to lead to increased throttling and decreased performance for the APM Server.

## Possible solution

We should investigate how to perhaps auto tune the `GOMAXPROCS` setting by setting it to the actual CFS CPU quota (if any). Uber has an `autogomaxprocs` library we should look into using: https://github.com/uber-go/automaxprocs

## Related issues

- Original issue: #1841
- Encountered while working on: #7540
- Golang: https://github.com/golang/go/issues/33803
- CFS explainer: https://engineering.indeedblog.com/blog/2019/12/unthrottled-fixing-cpu-limits-in-the-cloud/

**Comment by marclop** [comment]
Tried using [github.com/uber-go/automaxprocs](https://github.com/uber-go/automaxprocs) and ended up with the APM Server failing to start in managed mode with this log message:

```
Exiting: error initializing publisher: missing required field accessing 'output.elasticsearch.hosts'
```

**Comment by marclop** [comment]
I was able to run that branch locally using `runapm` and it worked just fine:

modified the `docker-compose.yml` services to include:

```yaml
  apm-server:
    image: elastic-agent-systemtest:8.3.0-7f585873-SNAPSHOT
    cpus: 2.7
    ports:
      - 8200:8200
    healthcheck:
      test: ["CMD-SHELL", "curl --fail https://localhost:8200/"]
      retries: 300
      interval: 1s
    environment:
      FLEET_ENROLL: 1
      FLEET_ENROLLMENT_TOKEN: REPLACEME
      FLEET_CA: /etc/pki/tls/certs/fleet-ca.pem
      FLEET_URL: https://fleet-server:8220
    depends_on:
      elasticsearch: { condition: service_healthy }
      kibana: { condition: service_healthy }
      fleet-server: { condition: service_healthy }
    volumes:
      - "./testing/docker/fleet-server/ca.pem:/etc/pki/tls/certs/fleet-ca.pem"
```

```console
$ grep max /usr/share/elastic-agent/state/data/logs/default/apm-server-20220506-1.ndjson
{"log.level":"info","@timestamp":"2022-05-06T03:47:56.757Z","log.logger":"beat","log.origin":{"file.name":"instance/beat.go","file.line":1076},"message":"Go runtime info","service.name":"apm-server","system_info":{"go":{"os":"linux","arch":"arm64","max_procs":4,"version":"go1.17.9"},"ecs.version":"1.6.0"}}
{"log.level":"error","@timestamp":"2022-05-06T03:47:56.771Z","log.logger":"beater","log.origin":{"file.name":"maxprocs/maxprocs.go","file.line":47},"message":"maxprocs: Updating GOMAXPROCS=2: determined from CPU quota","service.name":"apm-server","ecs.version":"1.6.0"}
```
