### ISSUE TITLE
APM server 8.5.1 won't start on Kubernetes 1.24

### ISSUE THREAD

**Issue by MeijerM1** [elastic/apm-server#9596]
**APM Server version** (`apm-server version`): 
8.5.1

**Description of the problem including expected versus actual behavior**:
APM server 8.5.1 is unable to start with the following error:
```
error initializing beat: error loading config file: open apm-server.yml: permission denied
```

**Steps to reproduce**:
Use ECK 2.4.0 to rollout APM server 8.5.1 on Kubernetes 1.24.

APM Definition:
```
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  labels:
    app: apm-server
  name: apm
  namespace: my-namespace
spec:
  version: 8.5.1
  count: 2
  kibanaRef:
    name: kibana
  elasticsearchRef:
    name: elasticsearch
  secureSettings:
    - secretName: apm-secret-settings
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    metadata:
      labels:
        app: apm-server
    spec:
      containers: 
      - name: apm-server
      automountServiceAccountToken: true
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              common.k8s.elastic.co/type: apm-server
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 2000
  config:
    setup.template.overwrite: true
    apm-server:
      ilm:
        enabled: "auto"
        setup:
          overwrite: true
          require_policy: false
    output:
      elasticsearch:
        hosts: ["some-url"]
        username: myUser
        password: myPassword 
```
**Provide logs (if relevant)**:
The `elasticsearch-internal-init-keystore` init container logs the following:
```
Initializing keystore.
+ keystore_initialized_flag=/usr/share/apm-server/data/elastic-internal-init-keystore.ok
+ [[ -f /usr/share/apm-server/data/elastic-internal-init-keystore.ok ]]
+ echo 'Initializing keystore.'
+ /usr/share/apm-server/apm-server keystore create --force
error initializing beat: error loading config file: open apm-server.yml: permission denied
```

**Comment by SansDK** [comment]
You should use the Elastic agent.

**Comment by simitt** [comment]
Thanks for filing the issue @MeijerM1. Have you upraded from a previous version (if so - which one) where your configuration was working or did you see this on a brand new deployment?

**Comment by MeijerM1** [comment]
@simitt We have upgraded from a working 8.4.3 deployment, with the exact same configuration.

**Comment by simitt** [comment]
Thanks for the update, we will look into this.

**Comment by simitt** [comment]
@MeijerM1 before diving into this, please note that setting up templates and configuring ILM is no longer supported in APM Server >= 8.0, since we switched to managed data streams. So basically this `config` section will have no effect:
```
    setup.template.overwrite: true
    apm-server:
      ilm:
        enabled: "auto"
        setup:
          overwrite: true
          require_policy: false
```
