### ISSUE TITLE
handleH2  error in apm log

### ISSUE THREAD

**Issue by b2ronn** [elastic/apm-server#9683]
I have an elasticsearch cluster in openshift 4.11 via the elastic operator 2.5.0.
apm server started as kind: ApmServer

```
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: test-apm
spec:
  config:
    apm-server.rum.enabled: true
    max_procs: 16
    apm-server.auth.anonymous.allow_agent:
      - rum-js
      - js-base
      - java
      - dotnet
      - php
      - opentelemetry/cpp
      - python
    apm-server.ssl.supported_protocols:
      - TLSv1.0
      - TLSv1.1
      - TLSv1.2
      - TLSv1.3
    apm-server.rum.allow_headers:
      - x-requested-with
    apm-server.aggregation.transactions.enabled: true
    apm-server.capture_personal_data: true
    logging.level: warning
    apm-server.auth.anonymous.enabled: true
    apm-server.rum.allow_origins:
      - '*'
    apm-server.logging.level: warning
  count: 4
  elasticsearchRef:
    name: elasticsearch
  http:
    service:
      metadata:
        annotations:
          service.beta.openshift.io/inject-cabundle: 'true'
          service.beta.openshift.io/serving-cert-secret-name: apmserver-openshift-tls
      spec: {}
    tls:
      certificate:
        secretName: apmserver-openshift-tls
      selfSignedCertificate:
        subjectAltNames:
          - dns: apm-server.somedomain.com
  kibanaRef:
    name: kibana
  podTemplate:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - name: apm-server
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 100Mi
  version: 8.5.2
```

and I get a lot of errors in the logs:

{"log.level":"error","@timestamp":"2022-11-27T22:44:11.270Z","log.logger":"beater.http","log.origin":{"file.name":"gmux@v0.2.0/mux.go","file.line":81},"message":"handleH2 (172.22.12.6:51292) returned an error: write tcp 172.21.79.53:8200->172.22.12.6:51292: write: connection reset by peer","service.name":"apm-server","ecs.version":"1.6.0"}

pc
eck 2.5.0
elastic/kibana/apm - 8.5.2
openshift 4.11
